ENGINE_TEMP_ID = "t1"
CABIN_TEMP_ID = "t2"
OUTSIDE_TEMP_ID = "t3"
INTAKE_AIR_ID = "t4"

REAR_LEFT_TIRE_ID = "b1"
REAR_RIGHT_TIRE_ID = "b2"
FRONT_LEFT_TIRE_ID = "b3"
FRONT_RIGHT_TIRE_ID = "b4"

GAS_PEDAL_POSITION_ID = "p1"
STERRING_WHEEL_ANGLE_ID = "p2"
ELECTRIC_VEHICLE_BATTERY_ID = "p3"
RADIO_VOLUME_ID = "p4"

REAR_LEFT_DIST_ID = "d1"
REAR_RIGHT_DIST_ID = "d2"
REAR_CENTER_DIST_ID = "d3"
FRONT_CENTER_DIST_ID = "d4"